### ISSUE TITLE
Loading, please wait... FOREVER

### ISSUE THREAD

**Issue by popecrunch** [madcowfred/wowthing-issues#10]
Hello hi yes. I'm stuck on Loading, please wait... no matter what I do.  This started when I refreshed Wowthing while WoW was in the process of closing down, so at first I worried it might have attempted to parse a data file that was in the process of being uploaded and therefore corrupted or garbage data.  Since then, I have tried, in all possible iterations of order:
- Logging into WoW and logging out to generate a new data file
- Uploading the file manually through the site instead of having Wowthing Sync do it
- Exiting my browser, killing all zombie processes, starting it again, clearing cache, closing it again, checking for zombie processes, starting it again
- Logging out of the site and back in again

Help?

**Comment by madcowfred** [comment]
This was a server-side bug, should be fixed now. I'll add an error message display for when this happens :\
