### ISSUE TITLE
Error on gaining garrison resources

### ISSUE THREAD

**Issue by popecrunch** [madcowfred/wowthing-issues#14]
Hi every time I collect garrison resources I get this error.  It started happening a few days ago when a whole grunch of addons updated, I don't remember which ones were updated, sorry :( Error text:

Date: 2015-10-29 17:50:12
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\WoWthing_Collector\Collector.lua line 231:
   attempt to index upvalue 'charData' (a nil value)
Debug:
   [C]: ?
   WoWthing_Collector\Collector.lua:231: ?()
   WoWthing_Collector\Collector.lua:399:
      WoWthing_Collector\Collector.lua:398
Locals:

AddOns:
  Swatter, v5.21e.5566 (SanctimoniousSwamprat)
  NPCScan, v6.2.2.3
  Ace3, v
  AckisRecipeList, v6.2.0.4
  Altoholic, vr165
  Arh, v1.4.4
  AskMrRobot, v28
  AucAdvanced, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21e.5566.5459(5.21e/embedded)
  AucMatchUndercut, v5.21e.5566.5507(5.21e/embedded)
  AucScanData, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatSales, v5.21e.5566.5476(5.21e/embedded)
  AucStatSimple, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21e.5566.5323(5.21e/embedded)
  AucUtilAHWindowControl, v5.21e.5566.5347(5.21e/embedded)
  AucUtilAppraiser, v5.21e.5566.5545(5.21e/embedded)
  AucUtilAskPrice, v5.21e.5566.5447(5.21e/embedded)
  AucUtilAutoMagic, v5.21e.5566.5537(5.21e/embedded)
  AucUtilCompactUI, v5.21e.5566.5550(5.21e/embedded)
  AucUtilEasyBuyout, v5.21e.5566.5507(5.21e/embedded)
  AucUtilFixAH, v5.21e.5566 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21e.5566.5417(5.21e/embedded)
  AucUtilPriceLevel, v5.21e.5566.5535(5.21e/embedded)
  AucUtilScanButton, v5.21e.5566.5403(5.21e/embedded)
  AucUtilScanFinish, v5.21e.5566.5515(5.21e/embedded)
  AucUtilScanProgress, v5.21e.5566.4979(5.21e/embedded)
  AucUtilScanStart, v5.21e.5566.5347(5.21e/embedded)
  AucUtilSearchUI, v5.21e.5566.5556(5.21e/embedded)
  AucUtilSimpleAuction, v5.21e.5566.5531(5.21e/embedded)
  AucUtilVendMarkup, v5.21e.5566.4828(5.21e/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v5.21e.5566 (SanctimoniousSwamprat)
  BonusRollPreview, v60200.27-Release
  Configator, v5.1.DEV.382(/embedded)
  CrossRealmAssist, v0.76 beta
  DataStore, vr55
  DataStoreAchievements, vr41
  DataStoreAgenda, vr22
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr35
  DataStoreContainers, vr51
  DataStoreCrafts, vr68
  DataStoreCurrencies, vr30
  DataStoreGarrisons, vr14
  DataStoreInventory, vr43
  DataStoreMails, vr43
  DataStorePets, vr38
  DataStoreQuests, vr35
  DataStoreReputations, vr36
  DataStoreSpells, vr26
  DataStoreStats, vr25
  DataStoreTalents, vr51
  DBMArchaeology, v
  DBMCore, v
  DBMDefaultSkin, v
  DBMGarrisonInvasions, v
  DBMPartyMoP, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMWorldEvents, v
  DebugLib, v5.1.DEV.337(/embedded)
  FlaskFoodCheck, v
  Gatherer, v5.0.0
  GreenWall, v1.6.5
  GTFO, v4.37.5
  HandyNotes, vv1.4.5
  HandyNotesDraenorTreasures, v1.16
  HandyNotesLorewalkers, v1
  HandyNotesTimelessIsleChests, v1.13
  HandynotesTimelessTreasures, v1.0.2
  Informant, v5.21e.5566 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.390(/embedded)
  LibPeriodicTable31, vv3.3.0.507
  MasterPlan, v0.75
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.143
  MogIt, v3.5.5
  MogItAccessories, v
  MogItHighlighter, vv1.3.2
  Omen, v3.1.11
  Paste, v1.4.3
  PetTracker, v6.2.3
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerJournal, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  Prat30, v3.5.20      
  Prat30Libraries, v
  RaidInfoBugFix, v6.2.0.3
  Skada, v1.4-32
  SlideBar, v5.21e.5566 (SanctimoniousSwamprat)
  Stubby, v5.21e.5566 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.389(/embedded)
  TomTom, vv60200-2.1.0
  TradeSkillMaster, v3X203
  TradeSkillMasterAccounting, v3X30
  TradeSkillMasterAppHelper, v3X4
  TradeSkillMasterAuctionDB, v3X8
  TradeSkillMasterAuctioning, v3X84
  TradeSkillMasterCrafting, v3X91
  TradeSkillMasterDestroying, v3X27
  TradeSkillMasterMailing, v3X42
  TradeSkillMasterShopping, v3X68
  TradeSkillMasterVendoring, v3X46
  TradeSkillMasterWarehousing, v3X14
  TradeSkillMasterWoWuction, v3X5
  TransmogSets, v
  WormholeCentrifuge, v1.4
  WoWDBProfiler, v
  WoWthingCollector, v0.6.2
  BlizRuntimeLib_enUS v6.2.2.60200 <none>
  (ck=f60)

**Comment by popecrunch** [comment]
Same issue, except now I have a character that cannot seem to give data to wowthing at all.  Things that trigger this error:
- gaining GR or oil
- bringing up many vendor interfaces, the repair guy on the mammoth seems to do it every time
- completing follower missions or shipyard missions
- collecting garrison work orders

Help?

Date: 2015-12-01 17:53:01
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\WoWthing_Collector\Collector.lua line 253:
   attempt to index upvalue 'charData' (a nil value)
Debug:
   [C]: ?
   WoWthing_Collector\Collector.lua:253: ?()
   WoWthing_Collector\Collector.lua:399:
      WoWthing_Collector\Collector.lua:398
Locals:

AddOns:
  Swatter, v5.21e.5566 (SanctimoniousSwamprat)
  WowheadLooter, v60013
  NPCScan, v6.2.3.3
  Ace3, v
  AckisRecipeList, v6.2.3.1
  Altoholic, vr165
  Arh, v1.4.5
  AskMrRobot, v31
  AucAdvanced, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21e.5566 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21e.5566.5459(5.21e/embedded)
  AucMatchUndercut, v5.21e.5566.5507(5.21e/embedded)
  AucScanData, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatHistogram, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatSales, v5.21e.5566.5476(5.21e/embedded)
  AucStatSimple, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21e.5566 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21e.5566.5323(5.21e/embedded)
  AucUtilAHWindowControl, v5.21e.5566.5347(5.21e/embedded)
  AucUtilAppraiser, v5.21e.5566.5545(5.21e/embedded)
  AucUtilAskPrice, v5.21e.5566.5447(5.21e/embedded)
  AucUtilAutoMagic, v5.21e.5566.5537(5.21e/embedded)
  AucUtilCompactUI, v5.21e.5566.5550(5.21e/embedded)
  AucUtilEasyBuyout, v5.21e.5566.5507(5.21e/embedded)
  AucUtilFixAH, v5.21e.5566 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21e.5566.5417(5.21e/embedded)
  AucUtilPriceLevel, v5.21e.5566.5535(5.21e/embedded)
  AucUtilScanButton, v5.21e.5566.5403(5.21e/embedded)
  AucUtilScanFinish, v5.21e.5566.5515(5.21e/embedded)
  AucUtilScanProgress, v5.21e.5566.4979(5.21e/embedded)
  AucUtilScanStart, v5.21e.5566.5347(5.21e/embedded)
  AucUtilSearchUI, v5.21e.5566.5556(5.21e/embedded)
  AucUtilSimpleAuction, v5.21e.5566.5531(5.21e/embedded)
  AucUtilVendMarkup, v5.21e.5566.4828(5.21e/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadPet, vv1.0.3
  BeanCounter, v5.21e.5566 (SanctimoniousSwamprat)
  BonusRollPreview, v60200.27-Release
  Configator, v5.1.DEV.382(/embedded)
  CrossRealmAssist, v0.76 beta
  DataStore, vr55
  DataStoreAchievements, vr41
  DataStoreAgenda, vr22
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr35
  DataStoreContainers, vr51
  DataStoreCrafts, vr68
  DataStoreCurrencies, vr30
  DataStoreGarrisons, vr14
  DataStoreInventory, vr43
  DataStoreMails, vr43
  DataStorePets, vr38
  DataStoreQuests, vr35
  DataStoreReputations, vr36
  DataStoreSpells, vr26
  DataStoreStats, vr25
  DataStoreTalents, vr51
  DBMArchaeology, v
  DBMCore, v
  DBMDefaultSkin, v
  DBMGarrisonInvasions, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  FlaskFoodCheck, v
  Gatherer, v5.0.0
  GreenWall, v1.6.5
  GTFO, v4.37.6
  HandyNotes, vv1.4.5
  HandyNotesDraenorTreasures, v1.16
  HandyNotesLorewalkers, v1
  HandyNotesTimelessIsleChests, v1.13
  HandynotesTimelessTreasures, v1.0.2
  Informant, v5.21e.5566 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.390(/embedded)
  LibPeriodicTable31, vv3.3.0.507
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.143
  MogIt, v3.5.5
  MogItAccessories, v
  MogItHighlighter, vv1.3.2
  Omen, v3.1.11
  Paste, v1.4.3
  PetTracker, v6.2.5
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerJournal, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  Prat30, v3.6.1      
  Prat30Libraries, v
  RaidInfoBugFix, v6.2.0.3
  Skada, v1.4-32
  SlideBar, v5.21e.5566 (SanctimoniousSwamprat)
  Stubby, v5.21e.5566 (SanctimoniousSwamprat)
  TipHelper, v5.12.DEV.389(/embedded)
  TomTom, vv60200-2.1.0
  TradeSkillMaster, v3X213
  TradeSkillMasterAccounting, v3X31
  TradeSkillMasterAppHelper, v3X5
  TradeSkillMasterAuctionDB, v3X10
  TradeSkillMasterAuctioning, v3X85
  TradeSkillMasterCrafting, v3X91
  TradeSkillMasterDestroying, v3X28
  TradeSkillMasterMailing, v3X43
  TradeSkillMasterShopping, v3X68
  TradeSkillMasterVendoring, v3X46
  TradeSkillMasterWarehousing, v3X14
  TradeSkillMasterWoWuction, v3X5
  TransmogSets, v
  WeakAuras, v2.1.0.17
  WhoPulled, v1.0.13
  WormholeCentrifuge, v1.4
  WoWDBProfiler, v
  WoWthingCollector, v0.6.2
  BlizRuntimeLib_enUS v6.2.3.60200 <none>
  (ck=f7d)

**Comment by madcowfred** [comment]
This was fixed at some point with an addon update.
