### ISSUE TITLE
Horde - Swift Warstrider mount is "incomplete" yet I own it in-game

### ISSUE THREAD

**Issue by Fluxflashor** [madcowfred/wowthing-issues#16]
In-game SS http://i.imgur.com/5YJUFWh.png
https://www.wowthing.org/u/Fluxflashor/#mounts

**Comment by madcowfred** [comment]
There's a neat bug with the Battle.net API where it sends the wrong ItemID for mounts - if you use the WoWthing_Collector addon + upload it it should find the mounts properly. I could probably hack around it on the backend side also :\

**Comment by Fluxflashor** [comment]
Never actually thought to check their API call! I did notice a few days ago the mount was set to collected on my account though so I'd consider this "bug" closed. 

Unless of course there's some other issue with the API retrieval overwriting data saved by the addon. I have been using the addon + savedvars uploader app (all those glorious Legion toys and other features woo!), but when I was using that I still didn't have the mount in my collection.
