### ISSUE TITLE
Reins of the Great *Color* Dragon Turtle

### ISSUE THREAD

**Issue by PlasticoX** [madcowfred/wowthing-issues#18]
Hello,

I do have all the Dragon Turtle's, http://us.battle.net/wow/en/character/illidan/Plasticobz/mount#status=is-collected

But in my wowthing profile is showing that do not own 3 of them:

https://www.wowthing.org/u/Plastico/#mounts

BTW, I wanna congratulate for the great job you do,  because so far is the only place that can list all the toy's currently in game accurately !

**Comment by madcowfred** [comment]
Weird, the API started returning a mix of the two different "sets" of turtle mount IDs. Should be fixed now.
