### ISSUE TITLE
Garrison Buildings?

### ISSUE THREAD

**Issue by nancikennedy** [madcowfred/wowthing-issues#21]
I've been trying this out, but can't seem to get the garrison buildings to show on any of my characters. I've done the whole log into each character and visit bank/void storage, uploaded the data file and synced with Battle.net. Am I missing something, or is this broken?

**Comment by madcowfred** [comment]
They were pretty broken. I've gone ahead and just removed the Garrison support for now, it's a giant pain and of very limited use (making bags?).
