### ISSUE TITLE
Unobtainable toys that are once again obtainable

### ISSUE THREAD

**Issue by Somarlane** [madcowfred/wowthing-issues#22]
Hello, I'm dropping by to let you know there are some toys in the Toy section that are once again obtainable. 

Bom'bay's Color-Seein' Sauce - Alliance vendor (no rep. req.)

Sen'jin Spirit Drum, Whole Body Shrinka', and Xan'tish's Flute - Horde vendor (no rep. req.)

The vendors themselves now exist outside of the phasing for the Broken Shore scenario as of 7.1.0, so they are easy to purchase.

**Comment by madcowfred** [comment]
Thanks, updated these.
