### ISSUE TITLE
Does The Website still work?

### ISSUE THREAD

**Issue by Miamiel** [madcowfred/wowthing-issues#23]
Hey, found your project yesterday and i found it rly awesome! But i followed your steps on https://www.wowthing.org/ and used your  WoWthing Sync. I linked Battle.net Account and i uploaded Data directly. But nothing is showing up. I logged in in wow, diff accs. Even Battle.net says : Updated 31m 19s ago, but no achievements or whatsoever is showing up. I thought maybe it would need some time, but i tried it yesterday and still nothing. So, do i have some issues or is the project dead? 

Greeting Mia :)

**Comment by madcowfred** [comment]
Hi there. Everything _seems_ to be working properly, it just doesn't seem to believe that you have any characters at all. Can you try re-adding the account via the wowthing site?

**Comment by Miamiel** [comment]
Geeeeeeez. Ok sry that i made a post for this. "try turning it off and on again" worked :-)
Dont know why, but after I re-added my account everything worked :) Thank you :)

**Comment by madcowfred** [comment]
Not sure what might have caused that but yay for it being fixed now.
