### ISSUE TITLE
7.2-related LUA error

### ISSUE THREAD

**Issue by Somarlane** [madcowfred/wowthing-issues#26]
Patch day being patch day.  This LUA error was generated when I opened my artifact weapon (Felo'melorn, fire mage) window after 7.2 was applied.

Date: 2017-03-28 19:37:54
ID: -3
Error occured in: Global
Count: 3
Message: ..\AddOns\WoWthing_Collector\Collector.lua line 1145:
   attempt to perform arithmetic on local 'currentRank' (a nil value)
Debug:
   WoWthing_Collector\Collector.lua:1145: ScanArtifactTraits()
   WoWthing_Collector\Collector.lua:1119:
      WoWthing_Collector\Collector.lua:1118
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:2420: SetUIPanel()
   ..\FrameXML\UIParent.lua:2238: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2132:
      ..\FrameXML\UIParent.lua:2128
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2914: ShowUIPanel()
   ..\FrameXML\UIParent.lua:1548:
      ..\FrameXML\UIParent.lua:953
   [C]: SocketInventoryItem()
   ..\FrameXML\PaperDollFrame.lua:1551: PaperDollItemSlotButton_OnModifiedClick()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:
self = <table> {
 ScanBuildings = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1277
 ScanFollowers = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1295
 UpdateGuildData = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:719
 ScanVoidStorage = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:944
 Login = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:629
 HookCollections = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1152
 CheckEquippedArtifact = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:831
 GetItemLevel = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1521
 ScanArtifactTraits = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1135
 GetDailyResetTime = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1491
 UpdateGuildBank = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:908
 ScanShipments = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1442
 ParseKeystoneLink = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:902
 ScanTradeSkills = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1084
 ScanReputations = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1240
 ScanOpenArtifact = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:780
 ScanBag = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:789
 HookArtifacts = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1110
 UpdateCharacterData = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:657
 ScanPets = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1216
 GetItemID = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1486
 ScanLockouts = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:964
 ScanHeirlooms = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1183
 ScanEquippedArtifact = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:764
 ScanMounts = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1200
 Cleanup = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:646
 ScanToys = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1257
 UpdateExhausted = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:750
 Logout = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:641
 ParseMissionTime = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1500
 ScanMythicDungeons = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1057
 ScanHonor = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1471
 ScanWeeklyQuests = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1073
 ScanMissions = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:1363
 ScanGuildBankTab = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:918
 Timer = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:514
 Initialise = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:582
 UpdateXP = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:742
 ParseArtifactLink = <function> defined @Interface\AddOns\WoWthing_Collector\Collector.lua:838
}
itemId = 128820
_ = 133959
artifact = <table> {
 numTraits = 38
 itemLevel = 879
 traits = <table> {
 }
 relics = <table> {
 }
 xp = 1214104
 bonusId = 730
}
powers = <table> {
 1 = 748
 2 = 749
 3 = 750
 4 = 751
 5 = 752
 6 = 753
 7 = 754
 8 = 755
 9 = 756
 10 = 757
 11 = 758
 12 = 759
 13 = 760
 14 = 761
 15 = 762
 16 = 763
 17 = 1340
 18 = 1372
 19 = 1533
 20 = 1534
 21 = 1535
 22 = 1536
 23 = 1640
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 748
 2 = 749
 3 = 750
 4

**Comment by Marabon** [comment]
Posting mine as well:

`Date: 2017-03-29 19:24:53
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WoWthing_Collector\Collector.lua line 891:
   attempt to perform arithmetic on local 'bonusCount' (a nil value)
Debug:
   [C]: ?
   WoWthing_Collector\Collector.lua:891: ParseArtifactLink()
   WoWthing_Collector\Collector.lua:834: CheckEquippedArtifact()
   WoWthing_Collector\Collector.lua:765: ScanEquippedArtifact()
   WoWthing_Collector\Collector.lua:528: Timer()
   WoWthing_Collector\Collector.lua:578:
      WoWthing_Collector\Collector.lua:578
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:

AddOns:
  KalielsTracker, v2.1.5
  Swatter, v7.0.4 (<%codename%>)
  WowheadLooter, v60014
  NPCScanOverlay, v7.1.0.1
  Accountant, v7.00.70000
  AckisRecipeList, v7.2.0.2
  AckisRecipeListQuickScan, v7.1.0.1
  Altoholic, vr177
  AngryKeystones, v
  Arh, v1.6.4
  AshranBuddy, v7.2.0
  AutoLootPlus, v1.2.0
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, vv7.2.3
  CollectMe, v2.9.3
  Configator, v5.1.DEV.406(/embedded)
  CrossRealmAssist, v0.81 beta
  DataStore, vr61
  DataStoreAchievements, vr44
  DataStoreAgenda, vr24
  DataStoreAuctions, vr46
  DataStoreCharacters, vr37
  DataStoreContainers, vr54
  DataStoreCrafts, vr75
  DataStoreCurrencies, vr33
  DataStoreGarrisons, vr19
  DataStoreInventory, vr47
  DataStoreMails, vr47
  DataStorePets, vr40
  DataStoreQuests, vr39
  DataStoreReputations, vr38
  DataStoreSpells, vr28
  DataStoreStats, vr27
  DataStoreTalents, vr57
  DBMCore, v7.2.0
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Gatherer, v7.0.4
  GatherMate2, v1.40
  GatherMateSharing, vv1.10
  HandyNotes, vv1.4.13
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesLunarFestival, vv1.4.4
  HandyNotesSummerFestival, vv1.3
  Keyed, v1.6.0
  LinksInChat, v1.2.9
  MasterPlanA, vA
  MPH, v1.0
  NomiCakes, v7.2.0.1
  NPCScan, v7.1.0.5
  Overachiever, v0.99.5
  Paste, v1.4.10
  Pawn, v2.2
  PersonalLootHelper, v1.26
  PetTracker, v7.1.4
  PetTrackerBreeds, v7.1.4
  PetTrackerConfig, v7.1.4
  PetTrackerJournal, v7.1.4
  PetTrackerSwitcher, v7.1.4
  PetTrackerUpgrades, v7.1.4
  PGFinder, v4.3
  PremadeGroupsFilter, v1.7
  QuestCompletist, v107
  Rarity, v1.0
  RarityOptions, v
  SavedInstances, v7.0.8
  SellJunk, v3.0.14
  Simulationcraft, v1.5.1
  Skada, v1.6.6
  SlideBar, v7.0.4 (<%codename%>)
  SuperGuildInvite, v7.6.0
  SushiSort, v7.0.0.0
  TomTom, vv70100-1.0.1
  TradeSkillMaster, vv3.6.25
  TradeSkillMasterAccounting, vv3.0.18
  TradeSkillMasterAppHelper, vv3.0.2
  TradeSkillMasterAuctionDB, vv3.1.16
  TradeSkillMasterAuctioning, vv3.0.14
  TradeSkillMasterCrafting, vv3.2.2
  TradeSkillMasterDestroying, vv3.1.5
  TradeSkillMasterMailing, vv3.0.13
  TradeSkillMasterShopping, vv3.4.5
  TradeSkillMasterVendoring, vv3.0.5
  TradeSkillMasterWarehousing, vv3.0.4
  WorldQuestGroupFinder, v0.22
  WorldQuestTracker, v
  WoWthingCollector, v0.8.6
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=92f)`

**Comment by madcowfred** [comment]
These should both be fixed in 0.9.0 - https://github.com/madcowfred/wowthing_collector/releases/tag/v0.9.0 or it will be on Curse soon(tm).
