### ISSUE TITLE
Max level Mythic+ completed this week not working

### ISSUE THREAD

**Issue by Marabon** [madcowfred/wowthing-issues#28]
Max level Mythic+ completed this week doesn't seem to be properly updating.

Mine is stuck on 0 for all my characters.
The keystone the characters have works though.

**Comment by madcowfred** [comment]
Fixed in addon 0.9.2, either at https://github.com/madcowfred/wowthing_collector/releases/tag/v0.9.2 or Curse when it updates. Sorry for the epic delay :(
