### ISSUE TITLE
Upload Error: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by Bogmore** [madcowfred/wowthing-issues#29]
I am trying to upload the file which is 1,496KB and the error I get is "413 Request Entity Too Large nginx"

I have a lot of alts.

**Comment by Bogmore** [comment]
And can I make a suggestion, You link the realm name to either the WoW forums or to Realm Pop.

**Comment by madcowfred** [comment]
The upload size should be fixed now, I only really test uploads using wowthing-sync and that cheats and uses compression.
