### ISSUE TITLE
Multiple WoW accounts on the same Battle.net account?

### ISSUE THREAD

**Issue by JTF195** [madcowfred/wowthing-issues#3]
Not sure if this is supported or not, but I have two WoW accounts on my Battle.net account, and it appears as though only the characters on one of them are being parsed and displayed on the site.

**Comment by madcowfred** [comment]
Hm, they should all display - one of the early testers has 3 WoW accounts on a single Battle.net account and his list has alll 9 million characters on it :|

**Comment by Zaynah** [comment]
Works for me. All my characters are displayed. 

Unfortunately for me, the Windows-Sync tool does not seem to pick up the additional accounts. It only uploads the LUA files from the first account.

**Comment by madcowfred** [comment]
/necro

Sync seems to work fine on my multiple accounts (RAF mounts are important), though it might freak out if you log both out at the same time.

**Comment by madcowfred** [comment]
/necro2 - I did fix the multiple accounts thing eventually, Sync will queue uploads. Closing this since I kind of forgot.
