### ISSUE TITLE
Underlight Angler progress tracking

### ISSUE THREAD

**Issue by MightBeChris** [madcowfred/wowthing-issues#31]
Would be nice to have this tracked on the Progress page if possible.

**Comment by madcowfred** [comment]
What is actually involved in getting this? I haven't gotten around to fishing yet :|

**Comment by MightBeChris** [comment]
http://www.wowhead.com/the-underlight-angler-a-step-by-step-guide-to-obtaining-legions-fishing-artifact

It requires getting the "Bigger Fish to Fry" achievement and then fishing up a quest object called "Luminous Pearl" then doing the quest/scenario that results.  It's 18 rare fish for the achievement and then a shortish quest.  The biggest thing to track would the the achievement (id=10596) as it is per toon.  Since the artifact has several QoL improvements beyond fishing (water walking, water breathing, swim speed boost) that work outside Legion zones it'd be nice to see how close a toon is with the rest of our progress.

**Comment by madcowfred** [comment]
Hi. Slightly slow, but I've finally added support for this - see Progress>Legion>Artifacts. You'll need the latest version of the addon (v7.3.5.6), either from GitHub or the Twitch client shortly.
