### ISSUE TITLE
WoWthing Collector Error Artifact Fishing Rod

### ISSUE THREAD

**Issue by Marabon** [madcowfred/wowthing-issues#33]
Hey,

 the WoWthing Collector addon threw an error when I equipped my artifact fishing rod.

Hope this information helps in pinpointing what happened.

Error:

> 1x WoWthing_Collector\Collector.lua:816: attempt to index field '?' (a nil value)
> WoWthing_Collector\Collector.lua:816: in function 'ScanEquippedArtifact'
> WoWthing_Collector\Collector.lua:569: in function 'Timer'
> WoWthing_Collector\Collector.lua:619: in function <WoWthing_Collector\Collector.lua:619>
> SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>
> 
> Locals:
> self = <table> {
>  ScanBuildings = <function> defined @WoWthing_Collector\Collector.lua:1371
>  ScanFollowers = <function> defined @WoWthing_Collector\Collector.lua:1389
>  UpdateGuildData = <function> defined @WoWthing_Collector\Collector.lua:765
>  ScanVoidStorage = <function> defined @WoWthing_Collector\Collector.lua:1016
>  Login = <function> defined @WoWthing_Collector\Collector.lua:674
>  HookCollections = <function> defined @WoWthing_Collector\Collector.lua:1246
>  CheckEquippedArtifact = <function> defined @WoWthing_Collector\Collector.lua:880
>  GetItemLevel = <function> defined @WoWthing_Collector\Collector.lua:1601
>  ScanArtifactTraits = <function> defined @WoWthing_Collector\Collector.lua:1229
>  GetDailyResetTime = <function> defined @WoWthing_Collector\Collector.lua:1585
>  UpdateGuildBank = <function> defined @WoWthing_Collector\Collector.lua:980
>  ScanShipments = <function> defined @WoWthing_Collector\Collector.lua:1536
>  ParseKeystoneLink = <function> defined @WoWthing_Collector\Collector.lua:972
>  ScanTradeSkills = <function> defined @WoWthing_Collector\Collector.lua:1178
>  ScanReputations = <function> defined @WoWthing_Collector\Collector.lua:1334
>  ScanOpenArtifact = <function> defined @WoWthing_Collector\Collector.lua:826
>  ScanBag = <function> defined @WoWthing_Collector\Collector.lua:835
>  ScanCriteria = <function> defined @WoWthing_Collector\Collector.lua:1036
>  HookArtifacts = <function> defined @WoWthing_Collector\Collector.lua:1204
>  UpdateCharacterData = <function> defined @WoWthing_Collector\Collector.lua:702
>  ScanPets = <function> defined @WoWthing_Collector\Collector.lua:1310
>  GetItemID = <function> defined @WoWthing_Collector\Collector.lua:1580
>  ScanLockouts = <function> defined @WoWthing_Collector\Collector.lua:1054
>  ScanQuests = <function> defined @WoWthing_Collector\Collector.lua:1162
>  ScanHeirlooms = <function> defined @WoWthing_Collector\Collector.lua:1277
>  ScanEquippedArtifact = <function> defined @WoWthing_Collector\Collector.lua:810
>  ScanMounts = <function> defined @WoWthing_Collector\Collector.lua:1294
>  Cleanup = <function> defined @WoWthing_Collector\Collector.lua:691
>  ScanToys = <function> defined @WoWthing_Collector\Collector.lua:1351
>  UpdateExhausted = <function> defined @WoWthing_Collector\Collector.lua:796
>  Logout = <function> defined @WoWthing_Collector\Collector.lua:686
>  ScanMythicDungeons = <function> defined @WoWthing_Collector\Collector.lua:1147
>  ParseMissionTime = <function> defined @WoWthing_Collector\Collector.lua:1594
>  ScanHonor = <function> defined @WoWthing_Collector\Collector.lua:1565
>  ScanMissions = <function> defined @WoWthing_Collector\Collector.lua:1457
>  Initialise = <function> defined @WoWthing_Collector\Collector.lua:623
>  Timer = <function> defined @WoWthing_Collector\Collector.lua:555
>  UpdateXP = <function> defined @WoWthing_Collector\Collector.lua:788
>  ParseArtifactLink = <function> defined @WoWthing_Collector\Collector.lua:887
>  ScanGuildBankTab = <function> defined @WoWthing_Collector\Collector.lua:990
> }
> itemId = 133755
> _ = nil
> _ = "Underlight Angler"
> _ = 1053367
> powerAvailable = 250
> traitsPurchased = 12
> (*temporary) = nil
> (*temporary) = 6
> (*temporary) = "attempt to index field '?' (a nil value)"
> wwtc = <table> {
>  ScanBuildings = <function> defined @WoWthing_Collector\Collector.lua:1371
>  ScanFollowers = <function> defined @WoWthing_Collector\Collector.lua:1389
>  UpdateGuildData = <f

**Comment by madcowfred** [comment]
I've added Underlight Angler to the artifact list in the newest version, let me know if that fixes things. It's difficult to test since I don't have this one still :(

**Comment by Marabon** [comment]
I've tried equipping the rod, and relogging and re-equipping it etc but I'm not getting the error. Can't confirm if it's fixed or if it was an odd one-time thing. Hopefully it fixes it :)
Thanks!
