### ISSUE TITLE
Guild Support (Banks, Rosters, Etc)

### ISSUE THREAD

**Issue by Latem5** [madcowfred/wowthing-issues#35]
Apologies for the wall of text. I run a fairly large guild on US servers, and have been looking for something similar to WoWThing but from the perspective of community management! Love what you've got going so far - tracking my toons has been *super* helpful!

# **Guild Roster**
As stated in another suggestion, being able to import a guild roster (automatically or manually), and filter it based on teams (raid, pvp, etc.) would be nice for staff to track information.

## Guild Log
Throwing this feature under the "Guild Roster" section, because it's related. Being able to track the guild log can be important for guild masters who want to gauge how many members are joining and leaving over a given period of time, among other things.

- Joins, leaves, promotions, demotions, gkicks.
- Graphs showing these metrics (Member Count [1 Month], Member Leaves [1 Week])

# **Guild Bank**
There are currently a few in-game addons that do this, but the majority of them are outdated, or don't accomplish certain tasks.

All of this information can be sourced from the members of a guild that also use WoWThing, that way the data is as consistent/updated as possible. Once the guild roster is scanned, members of a guild would be encouraged by the staff to use WoWThing. When any member visits a guild bank, the updater scans the tabs, logs, etc., and updates the information.

## Tab Overview
Monitoring guild bank changes can be important for guilds that offer free items to members (such as bags), as well as guilds that provide their raiders with flasks, food, and potions, among other things.

- Withdrawls per X time per tab. (Ex: Consumables - Withdrawls [1 Week])
- Deposits per X time per tab. (Ex: Free Pets - Deposits [1 Month])
- Changes (withdrawals, deposits, moves, etc.) viewable in a filterable, extended log.
- Log can be filtered based on what the action was, what tab the action happened in, or which person performed the action.

## Money Overview
Since Cash Flow is no longer a part of the game, I'm finding that a lot of guilds are having trouble keeping up with member repairs and other financial aspects of running a community. Being able to (as accurately as possible) track the financial history of a guild is super important.

- Extended gold log (withdrawals, deposits, repairs, etc.)
- Graphs (similar to how UndermineJounral shows market graphs) for transactions and donations from various sources. (Ex: Filter - Repairs [1 Week] // Filter - Deposits [1 Month])
- Easy to read text facts: Current Gold, Average Repair Amount, Weekly High, Weekly Low, etc.
- Contributions and withdrawals (repairs) on a per-person basis that show in a filterable table, that way staff can see how much each member is contributing or using both in running total form, and over a given period of time (1 month, 1 week, 1 day, etc.)

**Comment by madcowfred** [comment]
This would be a huge amount of work, and you'd probably be better off with a completely different system for managing it.

**Comment by Marabon** [comment]
Old suggestion that's not as complex as this one: #1 

Would be nice to have some sort of guild feature within WoWthing, even if it's a simple one.
