### ISSUE TITLE
Unleashed Monstrosities / Keystone Master in Progress Area

### ISSUE THREAD

**Issue by causeyr** [madcowfred/wowthing-issues#37]
This would be a great addition in the progress area. This is the js example to retrieve the KSM data from the api:

var m0 = sum_dungeons_m - parseInt(mythic_plus2);
var m2_to_m5 = parseInt(mythic_plus2) - parseInt(mythic_plus5);
var m5_to_m10 = parseInt(mythic_plus5) - parseInt(mythic_plus10);
var m10_to_m15 = parseInt(mythic_plus10) - parseInt(mythic_plus15);
var m15p = parseInt(mythic_plus15);

reference: https://us.battle.net/forums/en/bnet/topic/20754926585

On a side note: It would cool to see current arena rating in Overview. KSM, Unleashed Monstrosities and Arena Rating are the only things I'm tracking without your site. Thank you so much!

**Comment by madcowfred** [comment]
Hm, I'll look at adding the two progress things - there's currently no storage for statistics so M+ data will probably have to come from addon. Arena rating is possible, I meant to add it at some point along with Prestige :<

**Comment by madcowfred** [comment]
Hi. Slightly slow, but I've finally added support for this - see Progress>Legion>Artifacts. You'll need the latest version of the addon (v7.3.5.6), either from GitHub or the Twitch client shortly.
