### ISSUE TITLE
No Reputation

### ISSUE THREAD

**Issue by Anzu4** [madcowfred/wowthing-issues#38]
I have uploaded my data via the sync as well as the manual link, but my character's reputation page has no information. I have gone to each alts reputation page and scrolled through it. I have logged off and exited WoW several times.

**Comment by madcowfred** [comment]
Ah, this started happening many weeks ago and I forgot to ever fix it. Oops :| It should be fixed now, check in an hour or so once the API process has a chance to chew through 25,000 characters.

**Comment by madcowfred** [comment]
Getting reports this is actually fixed so closing the issue.
