### ISSUE TITLE
Character link open in new tab

### ISSUE THREAD

**Issue by Marabon** [madcowfred/wowthing-issues#41]
Would be nice if clicking a character link would open it in a new tab.

`target="_blank"`

**Comment by madcowfred** [comment]
This is a bit of a weird one. I think _some_ of the links had it previously, but there's a (solvable) security issue with target="_blank" and also the fact that it's generally not recommended: https://css-tricks.com/use-target_blank/ . Ctrl-click (or the equivalent on Macs, whichever modifier key it is) seems easy enough to remember to use.

**Comment by Marabon** [comment]
Oh, I'm well aware of the CTRL-click (or right click open in new tab).
I was unaware of the security issue, and that there was a conscious choice behind the reasoning. I'm all good with continuing to use CTRL-Click to open them in new tabs.
Thanks for the reply, and this great site! :)
