### ISSUE TITLE
wowthing website login issue

### ISSUE THREAD

**Issue by khoinoor** [madcowfred/wowthing-issues#43]
I'm trying to log into wowthing.org website but it keep telling me username/pwd are incorrect... followed instruction for change pwd 3 times in a row, and after getting the message the pwd was successfully changed, when trying to log into the website I was getting again the same error... pls help

**Comment by madcowfred** [comment]
Hi. Are you trying to login using your username or your email address? It needs to be the username you chose when signing up. I'm not sure if the password reset actually works, I'll look into that tomorrow.
