### ISSUE TITLE
Honor levels

### ISSUE THREAD

**Issue by soulyouth** [madcowfred/wowthing-issues#47]
Any chance you could add a way to track honor across my alts, I want to be able to see which ones are close to unlocking the skin

**Comment by madcowfred** [comment]
Funnily enough the addon has supported gathering honor/prestige data for quite a long time, I just haven't gotten around to adding storage/display for it. I'll see if I can work out something that doesn't annoy me too much this week.

**Comment by madcowfred** [comment]
This is live now. Doesn't need an addon update, you just get the joy of logging in to all of your characters~
