### ISSUE TITLE
LUA Error.

### ISSUE THREAD

**Issue by g1zstar** [madcowfred/wowthing-issues#5]
1x WoWthing_Collector\Collector.lua:880: attempt to index upvalue 'charData' (a nil value)
WoWthing_Collector\Collector.lua:880: in function `ScanShipments'
WoWthing_Collector\Collector.lua:285: in function `?'
WoWthing_Collector\Collector.lua:319: in function <WoWthing_Collector\Collector.lua:318>

Locals:
self = <unnamed> {
 0 = <userdata>
}
wwtc = <table> {
 ScanBuildings = <function> defined @WoWthing_Collector\Collector.lua:755
 ScanBag = <function> defined @WoWthing_Collector\Collector.lua:526
 ScanFollowers = <function> defined @WoWthing_Collector\Collector.lua:769
 Initialise = <function> defined @WoWthing_Collector\Collector.lua:367
 GetItemID = <function> defined @WoWthing_Collector\Collector.lua:904
 ScanVoidStorage = <function> defined @WoWthing_Collector\Collector.lua:593
 Login = <function> defined @WoWthing_Collector\Collector.lua:404
 UpdateXP = <function> defined @WoWthing_Collector\Collector.lua:509
 ParseMissionTime = <function> defined @WoWthing_Collector\Collector.lua:918
 Cleanup = <function> defined @WoWthing_Collector\Collector.lua:416
 GetDailyResetTime = <function> defined @WoWthing_Collector\Collector.lua:909
 ScanToys = <function> defined @WoWthing_Collector\Collector.lua:743
 UpdateGuildBank = <function> defined @WoWthing_Collector\Collector.lua:559
 Logout = <function> defined @WoWthing_Collector\Collector.lua:411
 ScanShipments = <function> defined @WoWthing_Collector\Collector.lua:879
 UpdateExhausted = <function> defined @WoWthing_Collector\Collector.lua:515
 HookToyBox = <function> defined @WoWthing_Collector\Collector.lua:726
 ScanTradeSkills = <function> defined @WoWthing_Collector\Collector.lua:702
 ScanMissions = <function> defined @WoWthing_Collector\Collector.lua:805
 UpdateCharacterData = <function> defined @WoWthing_Collector\Collector.lua:428
 Timer = <function> defined @WoWthing_Collector\Collector.lua:329
 ScanLockouts = <function> defined @WoWthing_Collector\Collector.lua:611
 ScanGuildBankTab = <function> defined @WoWthing_Collector\Collector.lua:569
 UpdateGuildData = <function> defined @WoWthing_Collector\Collector.lua:488
}

**Comment by g1zstar** [comment]
not sure why this was happening but it happened after my SSD got full, fixed by deleting savedVariables.

**Comment by g1zstar** [comment]
Still having this problem.

**Comment by madcowfred** [comment]
It's pretty hard to work out why this happens, I only get it very occasionally (like once every few days). Does it happen regularly for you?

**Comment by g1zstar** [comment]
It happens pretty regularly, I cleared my LUA errors from BugGrabber yesterday and I already have 9 instances of this error. I am constantly reloading and logging in to another character though which is why it happens so much.

**Comment by madcowfred** [comment]
There's probably a fix for this in 0.6.0, and by fix I mean it just doesn't do anything if charData is bugged on load. It should mostly work though?
