### ISSUE TITLE
Oauth Server Error

### ISSUE THREAD

**Issue by LilliCat** [madcowfred/wowthing-issues#8]
I don't think this is related to the addon at all, but I was unable to find contact information.  I deleted my token and I was asked if I wanted to save my character data, so I left the box unchecked, but the character data was deleted anyway.  I try to add a new token and over the past few days, at several different times, I have received a 500 server error.  I upload my WoWthing_Collector.lua file and expect my information to show but it doesn't appear. (You don't appear to have any characters to show!)

This is for North America.  Other regions seem to work but they don't apply to me.

**Comment by madcowfred** [comment]
This Github page is for issues with the website, you found the right place.

It looks like Blizzard made a change to their OAuth system with no warning: http://us.battle.net/en/forum/topic/18300183303 . I've applied a fix and it should work again now.
