### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by Krdan** [madcowfred/wowthing-issues#9]
I suggest to add an option to change the account's password, it's a security best practice to regularly change passwords, thanks!

**Comment by Marabon** [comment]
This could indeed be very useful, and shouldn't be too hard to implement either.

**Comment by Marabon** [comment]
Lastpass is complaining I'm using a "weak" password on wowthing, would be great if we could get a change password feature in soon-ish. :) @madcowfred

**Comment by madcowfred** [comment]
This sure is an old ticket. It's actually kind of a terrible practice to regularly change passwords, as my series of work passwords can probably attest :p Long random strings from a password manager are the way to go!

... I've finally actually gotten around to adding this functionality, it took about 5 minutes total. Sorry for the minor delay. You can find it on the username dropdown in the top right.
